#!/usr/bin/env bash
# install ngix and have a file that returns the string "Hello World"

sudo apt-get update -y && \
sudo apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!\n"
sudo service nginx restart
