#!/usr/bin/env bash
# Configuring a new server

sudo apt-get update
sudo apt-get -y install nginx
sudo service ngnix start
sudo sed -i "/listen 80 default_server/a add_header X-Served-By $HOSTNAME;" /etc/ngnix/sites-available/default
echo "Hello World!" | sudo tee /usr/share/ngnix/html/index.html
sudo service ngnix restart
