#!/usr/bin/env bash
# installing the load balancer

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install haproxy
sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.original
sudo sed -i "a\listen 2073-lb-01\n\tbind *:80\n\tmode http\n\tbalance roundrobin\n\toption httpclose\n\toption forwardfor\n\tserver 2073-web-02 3.234.214.241 check\n\tserver 2073-web-01 3.231.228.75 check" /etc/haproxy/haproxy-cfg
sudo service haproxy start 