#!/usr/bin/env bash
# Writes 'I am alive!' indefinately to the file /tmp/my_process


sudo touch /var/run/myscript.pid
sudo bash -c 'echo $$ > /var/run/myscript.pid'

while true; do
    sudo bash -C 'echo "I am alive!" >> /tmp/my_process'
    sleep 2
done

