#!/usr/bin/env bash
# Writes 'I am alive!' indefinately to the file /tmp/my_process


sudo touch /tmp/my_process.pid
sudo bash -c 'echo $$ > /var/run/my_process.pid'

while true; do
    sudo bash -C 'echo "I am alive!" >> /tmp/my_process'
    sleep 2
done

