#!/usr/bin/env bash
# A script that displays the content of the file /etc/passwd
# It displays only the username, userid, and homedirectory path
# Use a while loop

input="/etc/passwd"
while IFS= read -r line; do
    echo "$line" | cut -d':' --field=1,3,6
done < "$input"
