#!/usr/bin/env bash
# This script prints "Best School" ten times
# using the while loop

COUNTER=10
while [ $COUNTER -ge 1 ]; do
    echo "Best School";
    if [ $COUNTER -eq 2 ]
    then
	echo "Hi"
    fi
    ((COUNTER--))
done
