#!/usr/bin/env bash
# This script prints numbers that range from 1 to 20 
# and enters some conditions in it.

COUNTER=0
while [ $COUNTER -lt 20 ]; do
    if [ $COUNTER -eq 4 ]
    then
	echo "bad luck from China"
    elif [ $COUNTER -eq 9 ]
    then
	echo "bad luck from Japan"
    elif [ $COUNTER -eq 17 ]
    then
	echo "bad luck from Italy"
    else
	echo $COUNTER
    fi
    ((COUNTER++))
done
