#!/usr/bin/env bash
# This script prints numbers that range from 1 to 20 
# and enters some conditions in it.

COUNTER=0
while [ $COUNTER -lt 20 ]; do
    ((COUNTER++))
    echo $COUNTER
    case $COUNTER in
    4) echo "bad luck from China";;
    9) echo "bad luck from Japan";;
    17) echo "bad luck from Italy";;
    esac
done
