#!/usr/bin/env bash
# This script prints "Best School" ten times
# using the while loop

COUNTER=1
while [ $COUNTER -le 20 ]; do
    if [ $COUNTER -eq 5 ]
    then
	echo "bad luck from China"
    elif [ $COUNTER -eq 10 ]
    then
	echo "bad luck from Japan"
    elif [ $COUNTER -eq 18 ]
    then
	echo "bad luck from Italy"
    else
	echo $COUNTER
    fi
    ((COUNTER++))
done
