#!/usr/bin/env bash
# This script prints "hour" and minutes
# using the while loop


HOUR=0
MINUTE=-1
while [ $HOUR -lt 13 ]; do
    ((MINUTE++))
    if [ $MINUTE -eq 0 ]
    then
	echo "HOUR: $HOUR"
    elif [ $MINUTE -ne 60 ]
    then
	echo $MINUTE
    else
	if [ $HOUR -ne 12 ]
        then
	    echo "HOUR: $((HOUR+1))"
	fi
	((HOUR++))
        MINUTE=0    
    fi
done
