#!/usr/bin/env bash
# This script configures my SSH client to the my need to connect it to a server
# without typing a password.
# The SSH client configuration is configured using the private key ~/.ssh/school
# It is also configured to refuse authentication using a password

Host *
#    ForwardAgent no
#    ForwardX11 yes
#    ForwardX11Trusted yes
#    RhostsRSAAuthentication no
#    PasswordAuthentication no
#    HostbasedAuthentication no
#    GSSAPIAuthentication no
#    GSSAPDelegateCredentials no
#    GSSAPIKeyExchange no
#    GSSAPITrustDNS no
#    BatchMode no
#    CheckHostIp yes
#    AddressFamily any
#    ConnectTimeout 0
#    StrictHostKeyChecking ask
#    IdentifyFile ~/.ssh/identity
#    IdentifyFile ~/.ssh/id_rsa
#    IdentifyFile ~/.ssh/id_dsa
#    port 22
#    protocol 2,1
#    Cipher3des
#    Cipher aes128-ctr,aes192-ctr,aes256-ctr,arcfour256,arcfour128,aes128-cbc,3des-cbc
#    MACs hmac-md5,hmac-shal,umac-64@openssh.com,hmac-ripemd160
#    EscapeChar ~
#    Tunnel no
#    TunnelDevice any:any
#    PermitLocalCommand no
#    VisualHostKey no
#    ProxyCommand ssh -q -W %h:%p gateway.example.com
#    RekeyLimit 1G 1h
     SendEnv LANG LC_*
     HashKnownHosts yes
     GSSAPIAuthentication yes
     GSSAPIDelegateCredentials no
     IdentityFile ~/.ssh/school
     PasswordAuthentication no

